### ISSUE TITLE
Complete location_items.csv using smaller official guide data

### ISSUE THREAD

**Issue by CarlosFdez** [gatheringhallstudios/MHWorldData#10]
The current version of location_items.csv is from Kiranico, which I believe used the (smaller) official guide. However, they didn't list the node type and node drop table (common/rare aka shiny). If anyone has that guide and is willing to add the information here, I'd certainly love the help.

The idea would be to add a `node_type` and `node_rarity` column. `node_type` would be ore, bones, redore, etc. `node_rarity` would be `common` or `shiny`.

Also, apparently some maps have "merged areas" for the spawning of certain nodes. If that's true, updating the specific entries to refer to the merged sum would be helpful. I hear this happens in Elder's Recess 5 and 6, so an area `5 or 6` would be the area of that node.

**Comment by tjulises** [comment]
Hello @gatheringhallstudios ,

I am a Graphic Designer looking to collaborate in projects like this!
I'd like to provide a logo that suits this project!
let me know if you are interested! Thanks!!!

**Comment by CarlosFdez** [comment]
Thank you for the offer, but unfortunately this is a data collection project, and we're mostly solid on images (outside of images that need to be manually collected...not designed...).

Good luck though.
