### ISSUE TITLE
Add Kulve Taroth's weapons

### ISSUE THREAD

**Issue by kennedyoliveira** [gatheringhallstudios/MHWorldData#12]
Hey!

Add Kulve Taroth's weapons, that will be pretty useful :)

Here are two links for the weapons:
[Taroth Weapons](https://docs.google.com/spreadsheets/d/1Wz-Td12VmqYZUKCvyIOr34k03VNXUF7qfJu35i6Sjws/edit#gid=2105552725)
[Taroth Weapons 2](https://docs.google.com/spreadsheets/d/1pnetXLgMSyF504Bv1gdpJ2YCkRhzKQVvj3uQpdXG0gA/edit#gid=0)

Both of the above links are community driven, there are no official source of this data to my knowledge, I could be wrong and that would be very good but unfortunately I think thats the best we have.

I'm farming kulve and using the first spreadsheet as a reference for things I'm looking after, and so far the data seems pretty accurate, I have around 30 ~ 50 weapons, and checked a good amount of them, they are present in the spreadsheet and with correct data.

Since the list is a spreadsheet it can be easily programmatic converted to the format you use.

Thanks for your awesome work so far :)

**Comment by CarlosFdez** [comment]
Thanks for the links.

Unfortunately the weapons section needs to be refactored. We recently changed from JSON to CSV, and the weapons are still a holdover from the older format. I'm planning on reworking that section once the [app](https://github.com/gatheringhallstudios/MHWorldDatabase) this project is for reaches a certain point in development.

However, once we get to that point, links like the above will be really helpful. Thanks for linking!

**Comment by CarlosFdez** [comment]
This can now be tackled via the binary merge module. We should have something regarding htis soon.

**Comment by CarlosFdez** [comment]
Done. Will be in the next version. Very very late but we finally caught up with everything else that needed to be done.
