### ISSUE TITLE
Maintenance Jewel is not included

### ISSUE THREAD

**Issue by lon9** [gatheringhallstudios/MHWorldData#21]
There isn't Maintenance Jewel in the list of decorations.

English: Maintenance Jewel 1
Japanese: 整備珠【１】
Chinese: 整備珠【１】
Korean: 정비주 【1】

**Comment by CarlosFdez** [comment]
Thank you for reporting this. I started the process of adding in, but doing so had me realize that the decoration chance calculation was outdated and needed tweaking. Will also need to work on that while I'm at it.

**Comment by CarlosFdez** [comment]
Just finished doing it! It, along with more accurate drop rates, will be available in the next release.
