### ISSUE TITLE
How to update the data in source_data/armors/armorset_*.csv?

### ISSUE THREAD

**Issue by rising-fallmoon** [gatheringhallstudios/MHWorldData#25]
How to update the data in source_data/armors/armorset_*.csv?
I run the code in merge.py and wrote some my own codes to do more process, but then I find the data of armorset was not updated like other files. How can I update them ?

**Comment by CarlosFdez** [comment]
@rising-fallmoon armorset_base is now updated, but not armorset bonus. It still uses the existing names in armorset_bonus as a key, but the rest of the data (including armor names) are now filled out.

I'd do armorset bonus but I don't know how the associations work and luckily there aren't that many unique armorset bonuses.
