### ISSUE TITLE
python merge.py binary update issue

### ISSUE THREAD

**Issue by maichongju** [gatheringhallstudios/MHWorldData#28]
(MHWorldData-UozLJLHE) F:\MHWorldData>python merge.py binary update
Binary armor data loaded
Existing Data loaded. Using existing armorset data to drive new armor data.
Writing list of armorset names (in order) to artifacts
Updating set data, keyed by the existing names in armorset_base.csv
Armorset entries updated
Updating armor
Armor files updated

Item files updated
Existing Data loaded. Using to update weapon info
Loaded initial weapon binary data data
Loaded great-sword weapon tree binary data
Loaded long-sword weapon tree binary data
Loaded sword-and-shield weapon tree binary data
Loaded dual-blades weapon tree binary data
Loaded hammer weapon tree binary data
Loaded hunting-horn weapon tree binary data
Loaded lance weapon tree binary data
Loaded gunlance weapon tree binary data
Loaded switch-axe weapon tree binary data
Loaded charge-blade weapon tree binary data
Loaded insect-glaive weapon tree binary data
Loaded light-bowgun weapon tree binary data
Loaded heavy-bowgun weapon tree binary data
Loaded bow weapon tree binary data
Skipping Twin Nails element data
Skipping Fire and Ice element data
**Could not find binary entry for Taroth Daggers "Fire"**
Weapon files updated

Item files updated

I see that "Could not find binary entry for Taroth Daggers "Fire", is it normal?

**Comment by CarlosFdez** [comment]
It may be related to https://steamcommunity.com/games/582010/announcements/detail/1769260276847699009

See if you have the latest chunk merged in.

I'll check out what's going on later if that's it, but I'm currently on another project in the meantime.

**Comment by CarlosFdez** [comment]
Looking at it again, and even though the announcement says it changed from blast to fire in naming, it instead swapped to blast in the latest files. I'll have to do some investigating, but I'd certainly love to receive some help here with figuring it out.

**Comment by CarlosFdez** [comment]
Asked for help, turns out Capcom actually messed up the names. I'd ignore the error and leave it as Fire, since they're likely to fix it in a future patch.

**Comment by CarlosFdez** [comment]
They ended up fixing it. Closing the issue.
