### ISSUE TITLE
[Question]: Iceborne Support?

### ISSUE THREAD

**Issue by DeveloperPaul123** [gatheringhallstudios/MHWorldData#30]
Hello, 

Just wanted to open up the discussion for Iceborne support in this project? Is the plan to wait until the PC release of MHW IB?

**Comment by jaysondc** [comment]
We don't plan to support Iceborne until PC release since our data pipeline relies on the chunk files being available. We're getting out of the business of manual entry since we support multiple languages now.

**Comment by CarlosFdez** [comment]
Yup, that's the plan. While it'd be possible to get some of the data ahead of time (if people were to contribute it to the database...since I'm on PC), stuff like skills would still be out of sync with the db version, and there's no implementation of versioning currently in place.

**Comment by DeveloperPaul123** [comment]
This all makes sense and is what I thought. Thanks!

**Comment by CarlosFdez** [comment]
I should mention btw, I'm down to accept all contributions that are related to monsters, equipment, or items. Even with automated data entry its still not 100% automatic, and it would speed things along. Its really only skills that make it difficult to add a new version.

**Comment by DeveloperPaul123** [comment]
Ok thanks for letting me know. Though, adding info for some of the new equipment will require the new skills as well.

**Comment by CarlosFdez** [comment]
Its fine to have placeholder skills in the meantime I think.

**Comment by Turqueso** [comment]
Iceborn has been out for a while. It's there any news on this update or something we can do to help?

**Comment by CarlosFdez** [comment]
Its a closed issue, but Iceborne is coming along, its just a lot of work. There's a beta version of the app on the playstore that has the current iceborne data. At this point what we're missing is charms (working on it), HH melodies, monster drops (would need help with this), and updated quests.
