### ISSUE TITLE
Build Error: expected an indented block

### ISSUE THREAD

**Issue by jacamp99** [gatheringhallstudios/MHWorldData#48]
In the most recent change of the mhdata/build/sql.py at line 655, an if statement was added without the correct indentation, stopping the build.

The error log:
$ pipenv run python build.py
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    from mhdata import build
  File "C:\Users\Jacob\Documents\GitHub\MHWorldData\mhdata\build\__init__.py", line 8, in <module>
    from .sql import build_sql_database
  File "C:\Users\Jacob\Documents\GitHub\MHWorldData\mhdata\build\sql.py", line 656
    weapon.skills.append(db.WeaponSkill(
    ^
IndentationError: expected an indented block

Solution:
I fixed it on my end by correcting the indentation.

Do you have any guidelines for proposing changes?

I'd also be happy to contribute more to the project as a whole. :)

**Comment by CarlosFdez** [comment]
In this particular case, I messed up uploading something (my source control tool was reporting strangely) so it should be easy to fix.

But as to contributing in general, there's no guideline, but if you want to make a suggestion or want to work on something, let me know via discord or via an issue and I'll try to respond.
